#!/bin/bash
# Create COMPLETE digest with ALL found items

OUT="Exports/complete_everything.md"

cat > "$OUT" << 'HEAD'
# Daily Business Dossier

**Complete Digest - All Items Found**

---

HEAD

# Reddit Section
echo "## 🟠 Reddit Business Leads (10)" >> "$OUT"
echo "" >> "$OUT"
cat /tmp/reddit.txt | awk '/^[0-9]+\./,/^$/ {print}' | head -60 >> "$OUT"
echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "" >> "$OUT"

# Twitter Section  
echo "## 🔵 Twitter Building Updates (15)" >> "$OUT"
echo "" >> "$OUT"
cat /tmp/twitter.txt | awk '/^[0-9]+\./,/^$/ {print}' | head -90 >> "$OUT"
echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "" >> "$OUT"

# YouTube - from latest digest
echo "## 🎥 YouTube AI Videos (4)" >> "$OUT"
echo "" >> "$OUT"
sed -n '/## 🎥 YouTube/,/^---$/p' Exports/full_digest_20260207_201709.md | head -20 >> "$OUT"
echo "" >> "$OUT"

# Moltbook - ALL 73 from latest digest
echo "## 🤖 Moltbook Agent Builds (73)" >> "$OUT"
echo "" >> "$OUT"
sed -n '/## 🤖 Moltbook/,/^## /p' Exports/full_digest_20260207_201709.md | head -300 >> "$OUT"
echo "" >> "$OUT"

# Health - from /tmp
echo "## 🟢 Health & Wellness" >> "$OUT"
echo "" >> "$OUT"
cat /tmp/health.txt | awk '/^\*\*[0-9]+\./,/^$/ {print}' | head -100 >> "$OUT"
echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "" >> "$OUT"

# RSS - from latest digest
echo "## 📰 RSS News Feed (23)" >> "$OUT"
echo "" >> "$OUT"
sed -n '/## 📰 RSS/,/Generated by/p' Exports/full_digest_20260207_201709.md | head -100 >> "$OUT"

echo "✅ Created complete digest: $OUT"

# Generate HTML
python3 << 'ENDPY'
from html_generator import DigestHTMLGenerator

with open('Exports/complete_everything.md', 'r') as f:
    md = f.read()

gen = DigestHTMLGenerator()
gen.archive_current_html()
html = gen.markdown_to_html(md, "Daily Business Dossier - Complete")
gen.save_html(html)
print("✅ HTML with ALL items generated!")
ENDPY

# Push
git add dossier.html Archive
git commit -m "Complete digest: ALL items from all platforms"
git push

echo "✅ PUSHED TO GITHUB!"
